name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install jest-silent-reporter
        run: npm install --save-dev jest-silent-reporter

      - name: Debug environment
        run: |
          node --version
          npm --version
          cat package.json
          cat tsconfig.json
          ls -la

      - name: Run unit tests with coverage
        run: npm run test:coverage -- --watch=false --silent --reporters=jest-silent-reporter
        env:
          JEST_SILENT_REPORTER_SHOW_SUMMARY: false
          JEST_SILENT_REPORTER_SHOW_COVERAGE: true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Build Angular app
        run: npm run build -- --configuration=production

  sonar:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v1.0.0
        with:
          args: >
            -Dsonar.projectKey=code-book
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: [build-test, sonar]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Deploy to Netlify
        run: npx netlify deploy --dir=dist/angular-starter --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
